# Generated by Django 5.1.3 on 2025-03-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlexa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('workplace', models.CharField(blank=True, max_length=200, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('foreign_languages', models.TextField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('hometown', models.CharField(blank=True, max_length=200, null=True)),
                ('certificates', models.TextField(blank=True, null=True)),
                ('warning_count', models.IntegerField(default=0)),
                ('day_start', models.DateField(blank=True, null=True)),
                ('day_end', models.DateField(blank=True, null=True)),
                ('block_count', models.IntegerField(default=0)),
                ('block_forever', models.BooleanField(default=False)),
                ('hide_date_of_birth', models.BooleanField(default=False)),
                ('hide_phone_number', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=False)),
                ('hide_address', models.BooleanField(default=False)),
                ('hide_workplace', models.BooleanField(default=False)),
                ('hide_qualifications', models.BooleanField(default=False)),
                ('hide_foreign_languages', models.BooleanField(default=False)),
                ('hide_hobbies', models.BooleanField(default=False)),
                ('hide_hometown', models.BooleanField(default=False)),
                ('hide_certificates', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
